/*
 * AtlasGenView.java
 */
package atlasgen;

import com.sun.net.ssl.internal.ssl.Debug;
import org.jdesktop.application.Action;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JTextField;

/**
 * The application's main frame.
 */
public class AtlasGenView extends FrameView {

    public static int imageWidth;
    public static int imageheight;
    public static int imageSplitX = 1;
    public static int imageSplitY = 1;
    public static String filename;
    public static String dir;
    public static DefaultListModel lm = new DefaultListModel();
    public JTextField saveAs = new JTextField("salam");

    public AtlasGenView(SingleFrameApplication app) {
        super(app);

        initComponents();
        
//        imagePanel1.setBackground(Color.red);
//        imagePanel1.setForeground(Color.red);
        // status bar initialization - message timeout, idle icon and busy animation, etc
        
        // connecting action tasks to status bar via TaskMonitor
        
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = AtlasGenApp.getApplication().getMainFrame();
            aboutBox = new AtlasGenAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        AtlasGenApp.getApplication().show(aboutBox);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        imagePanel1 = new atlasgen.imagePanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        fileNameLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        widthLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        heightLabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        preFillText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        frameList = new javax.swing.JList();
        jButton3 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();

        mainPanel.setName("mainPanel"); // NOI18N
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(atlasgen.AtlasGenApp.class).getContext().getResourceMap(AtlasGenView.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setName("jLabel1"); // NOI18N
        mainPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 140, 100, 20));

        jTextField1.setAlignmentX(0.0F);
        jTextField1.setAlignmentY(0.0F);
        jTextField1.setName("jTextField1"); // NOI18N
        mainPanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 230, 100, 20));

        jTextField2.setAlignmentX(0.0F);
        jTextField2.setAlignmentY(0.0F);
        jTextField2.setName("jTextField2"); // NOI18N
        mainPanel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 260, 100, 20));

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setAlignmentY(0.0F);
        jLabel2.setName("jLabel2"); // NOI18N
        mainPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 100, 20));

        imagePanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        imagePanel1.setName("imagePanel1"); // NOI18N
        imagePanel1.setPreferredSize(new java.awt.Dimension(400, 400));
        imagePanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagePanel1MouseClicked(evt);
            }
        });
        imagePanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        mainPanel.add(imagePanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 610, 460));

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateXMLFile(evt);
            }
        });
        mainPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 330, 100, 30));

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        mainPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 200, 100, 20));

        fileNameLabel.setName("fileNameLabel"); // NOI18N
        mainPanel.add(fileNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 140, 100, 20));

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        mainPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 170, 100, 20));

        widthLabel.setText(resourceMap.getString("widthLabel.text")); // NOI18N
        widthLabel.setName("widthLabel"); // NOI18N
        mainPanel.add(widthLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 200, 100, 20));

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        mainPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 230, 100, 20));

        heightLabel.setText(resourceMap.getString("heightLabel.text")); // NOI18N
        heightLabel.setName("heightLabel"); // NOI18N
        mainPanel.add(heightLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 170, 100, 20));

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setSplits(evt);
            }
        });
        mainPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 290, 100, 30));

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        mainPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 260, 100, 20));

        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N
        mainPanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 100, 30));

        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setName("jButton5"); // NOI18N
        mainPanel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 100, 30));

        jButton6.setText(resourceMap.getString("jButton6.text")); // NOI18N
        jButton6.setName("jButton6"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openImageEvt(evt);
            }
        });
        mainPanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, 100, 30));

        jButton7.setText(resourceMap.getString("jButton7.text")); // NOI18N
        jButton7.setName("jButton7"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSelectedFrame(evt);
            }
        });
        mainPanel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 100, 30));

        preFillText.setName("preFillText"); // NOI18N
        mainPanel.add(preFillText, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 390, 20));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        frameList.setName("frameList"); // NOI18N
        jScrollPane1.setViewportView(frameList);

        mainPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 490));

        jButton3.setLabel(resourceMap.getString("jButton3.label")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoFillListEvt(evt);
            }
        });
        mainPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 100, 40));

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(atlasgen.AtlasGenApp.class).getContext().getActionMap(AtlasGenView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setComponent(mainPanel);
        setMenuBar(menuBar);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteSelectedFrame(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSelectedFrame
        // TODO add your handling code here:
        int i = frameList.getSelectedIndex();
        lm.removeElementAt(i);
    }//GEN-LAST:event_deleteSelectedFrame

    private void openImageEvt(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openImageEvt
        // TODO add your handling code here:


        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File("C:\\Users\\ken\\Desktop\\resource\\images"));
        fc.showDialog(this.getComponent(), "open");
        //            if (!fc.isValid())
        //                return;
        //            if (fc.getSelectedFile().getName() == null)
        //                return;
        filename = fc.getSelectedFile().getName();
        dir = fc.getSelectedFile().getPath();
        //            scrollImagePanel1.setImage(dir);
        imagePanel1.setImage(dir);

        imagePanel1.repaint();
        fileNameLabel.setText(filename);
        imageWidth = imagePanel1.getImageWidth();
        imageheight = imagePanel1.getImageheight();
        widthLabel.setText(Integer.toString(imageWidth));
        heightLabel.setText(Integer.toString(imageheight));
        Debug.println(fc.getSelectedFile().getPath(), fc.getSelectedFile().getName());
    }//GEN-LAST:event_openImageEvt

    private void autoFillListEvt(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoFillListEvt
        // TODO add your handling code here:
        String str = preFillText.getText();
        String list[] = str.split(" ");
        lm.clear();
        for (int i = 0; i < list.length; i++) {
            lm.addElement(list[i]);

        }
        frameList.setModel(lm);
}//GEN-LAST:event_autoFillListEvt

    private void setSplits(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setSplits
        // TODO add your handling code here:
        imageSplitX = Integer.parseInt(jTextField1.getText());
        imageSplitY = Integer.parseInt(jTextField2.getText());
        imagePanel1.repaint();
}//GEN-LAST:event_setSplits

    private void generateXMLFile(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateXMLFile
        // TODO add your handling code here:
        imageSplitX = Integer.parseInt(jTextField1.getText());
        imageSplitY = Integer.parseInt(jTextField2.getText());

        WriteXMLFile xmf = new WriteXMLFile(dir, filename);
}//GEN-LAST:event_generateXMLFile

    private void imagePanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagePanel1MouseClicked
        // TODO add your handling code here:

        int sx = imagePanel1.getWidth();
        int sy = imagePanel1.getHeight();

        int isx = (int) (sx / imageSplitX);
        int isy = (int) (sx / imageSplitY);
        int fx = 1 + (evt.getX() / isx);
        int fy = 0 + (evt.getY() / isy);
        int fi = (fy * imageSplitX) + fx;
        //            System.out.print(/*Integer.toString((fx*isx)+fy)*/ fx + " " + fy + "\n"));
        //            System.out.print(Integer.toString(fx) + " " + Integer.toString(fy) + "\n");
        System.out.print(Integer.toString(fi) + "\n");
        //            frameList.add
        //            frameList.getModel().

        lm.addElement(fi - 1);
        frameList.setModel(lm);

    }//GEN-LAST:event_imagePanel1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JList frameList;
    private javax.swing.JLabel heightLabel;
    private atlasgen.imagePanel imagePanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTextField preFillText;
    private javax.swing.JLabel widthLabel;
    // End of variables declaration//GEN-END:variables
   
    private JDialog aboutBox;
}
